### PR TITLE
fix: incorrect argument passing to git push

### LINKED ISSUE #573: [Bug]: No longer works with default push settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Starting with 2.3, the following config fails:

```
name: template sync
on:
  # run every day at midnight
  schedule:
    - cron: '0 0 * * *'
  # manually trigger the workflow
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.INFRA_SYNC_TOKEN }}
      - name: actions-template-sync
        uses: AndreasAugustin/actions-template-sync@v2
        with:
          github_token: ${{ secrets.INFRA_SYNC_TOKEN }}
          source_repo_path: "pinginc/template-infra"
          source_repo_ssh_private_key: ${{ secrets.INFRA_TEMPLATE_SYNC_TOKEN }}
          is_pr_cleanup: true
```

### Expected Behavior

I expected this to work as it did in 2.2.3

### Current Behavior

The error that occurs is:

```
  ::info::push changes
  error: src refspec origin does not match any
  error: failed to push some refs to ' --set-upstream'
```

### Steps To Reproduce

Any configuration that does not end up with additional flags for `git push`

### Possible Solution

Rewrite the function  at https://github.com/AndreasAugustin/actions-template-sync/blob/7cd796fa1c887cb432d6a1d37e78172320131953/src/sync_template.sh#L290-L309

### Additional Information/Context

_No response_

### Template sync version Version

2.4.0

### PR DESCRIPTION
**Pull request by icco**
# Description

Close #573 

Correct way to handle bash arguments is using bash array.

Tested with following script

```
#!/bin/bash
set -ex

function push () {
  local branch=$1
  local is_force=$2
  local is_with_tags=$3

  args=(--set-upstream origin "${branch}")

  if [ "$is_force" == true ] ; then
    args+=(--force)
  fi

  if [ "$is_with_tags" == true ] ; then
    args+=(--tags)
  fi

  git push "${args[@]}"
}

push "main" false false
push "main" true false
push "main" false true
push "main" true true
```

## Remark

For automation please see [closing-issues-using-keywords](
    https://help.github.com/en/articles/closing-issues-using-keywords)

### CODE REVIEW

**Comment by AndreasAugustin** [comment]
@all-contributors please add @icco for bug and code

File: src/sync_template.sh [hunk 1]
```diff
@@ -293,19 +293,19 @@ function push () {
   local is_force=$2
   local is_with_tags=$3
 
-  local additional_params=" "
+  args=(--set-upstream origin "${branch}")
 
   if [ "$is_force" == true ] ; then
     warn "forcing the push."
-    additional_params="${additional_params}--force "
+    args+=(--force)
```
Comment (AndreasAugustin) [inline src/sync_template.sh:300]: thanks a bunch for the PR! :rocket: 
just thought about the order of the arguments for `git push`.
Like `args+=(--force args[@])`

It definititly works with your change. Was just out of a convenience part.
But let's keep it like that :ninja:

**Review by AndreasAugustin — APPROVED** [review]
