### PR TITLE
fix(sync-template): fix issue with .templatesyncignore conflicts

### LINKED ISSUE #250: Restore .templatesyncignore in case of another version in the tpl repository
**Describe the bug**
In case you also handle a `.templatesyncignore` in your tpl repository, for an initial setup or because ~80% of your repositories use a fixed version, you run into merge issues if you have a change in a ignored file.

**To Reproduce**

1. Create tpl repository and include the following files:
  - foo.txt
  - bar.txt
  - foobar.txt
  - .templatesyncignore: |
  foo.txt
 
2. Create child repository and include sync worksflow and the following files:
  - foo.txt
  - bar.txt
  - foobar.txt
  - .templatesyncignore: |
  foo.txt
  bar.txt

3. push a change to the tpl repository `bar.txt` file
4. Execute sync action

**Expected behaviour**
Expected behaviour is now that you have no changes/PR by the actions-template-sync, but you get the change of the bar.txt because the `.templatesyncignore` will be overwritten from the tpl repo before the [git reset](https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L73)

 **Additional context**

A possible solution which I will try out now in https://github.com/AndreasAugustin/actions-template-sync/blob/main/src/sync_template.sh#L58 is this snippet:

```sh
# restore TEMPLATE_SYNC_IGNORE_FILE_NAME in case of a change/diff
# from the tpl repository. The original file in the final repo always wins.
if ! git diff --exit-code "${TEMPLATE_SYNC_IGNORE_FILE_NAME}"; then
  echo "::group::restore ignore file because of incomming changes from tpl repository"
  git restore "${TEMPLATE_SYNC_IGNORE_FILE_NAME}"
  echo "::endgroup::"
fi
```

### PR DESCRIPTION
**Pull request by msiebeneicher**
# Description

Close #250 

Fix issue #250 with overwritten .templatesyncignore files from tpl repository.

### CODE REVIEW

File: src/sync_template.sh [hunk 1]
```diff
@@ -52,10 +52,32 @@ echo "::endgroup::"
...
+
 echo "::debug::pull changes from template"
 git pull "${SOURCE_REPO}" --allow-unrelated-histories --squash --strategy=recursive -X theirs
 echo "::endgroup::"
 
+if [ -s ${TEMPLATE_SYNC_IGNORE_FILE_NAME} ]
+then
+  echo "::group::restore ignore file"
+  # restore ignore file. the ignore file in the final repo always wins
+  mv -f "${TEMPLATE_SYNC_IGNORE_FILE_NAME}.tmp" "${TEMPLATE_SYNC_IGNORE_FILE_NAME}"
```
Comment (AndreasAugustin) [inline src/sync_template.sh:70]: The current approach definitely works in terms of the file.
@msiebeneicher I guess this will add a new commit to the file?

Maybe smth like `git checkout HEAD~1 -- ${TEMPLATE_SYNC_IGNORE_FILE_NAME}`  will reset it to current version so that no new commit will be done.

I did not test it (yet).

Comment (AndreasAugustin) [reply src/sync_template.sh:70]: Ok I have a possible solution now

```bash
git reset .templatesyncignore
git checkout -- .templatesyncignore
```

this should do the trick

Comment (msiebeneicher) [reply src/sync_template.sh]: Nice catch! 10 times smarter than the other way! 👍 
Updated the code now with your solution.

**Review by AndreasAugustin — APPROVED** [review]

**Comment by AndreasAugustin** [comment]
@all-contributors
please add @msiebeneicher for bug
