### PR TITLE
fix: quote PR title

### LINKED ISSUE #193: Fails to create PRs with spaces in PR title
**Describe the bug**
This currently fails to create PRs with spaces in the PR title

**To Reproduce**
Use this action to create PRs with spaces in the title (which includes the default PR title). You'll see the following error:
Screen Shot 2022-08-26 at 2 20 41 PM

**Expected behavior**
The action should successfully create a PR with the given PR title

 **Additional context**
 The PR title given to the `gh create PR` command needs to be enclosed in quotes if it contains spaces

### PR DESCRIPTION
**Pull request by JTunis**
# Description

Closes #193

PR titles need to be surrounded by quotes since they will include spaces

### CODE REVIEW

File: src/sync_template.sh [hunk 1]
```diff
@@ -85,7 +85,7 @@ echo "::endgroup::"
 
 echo "::group::create pull request"
 gh pr create \
-  --title ${PR_TITLE} \
+  --title "${PR_TITLE}" \
```
Comment (AndreasAugustin) [inline src/sync_template.sh:88]: thanks! Did not see that within PR :+1:

**Review by AndreasAugustin — APPROVED** [review]
